name: OneRoom
options:
  deploymentTarget:
    iOS: "15.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
targets:
  OneRoom:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Assets.xcassets
      - path: Web
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lukayara.oneroom100monsters
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: "NO"
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: One Room, 100 Monsters
        CFBundleName: OneRoom
        UILaunchScreen: {}
        UIUserInterfaceStyle: Dark
        UIViewControllerBasedStatusBarAppearance: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
