(() => {
  'use strict';

  const W = 1000, H = 562, WALL = 28;
  const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
  const $ = (s) => document.querySelector(s);
  const ui = { overlay: $('#overlay'), hud: $('#hud'), toast: $('#toast'), pause: $('#pause-button'), health: $('#health-fill'), healthText: $('#health-text'), wave: $('#wave-value'), score: $('#score-value'), kills: $('#kill-count'), timer: $('#timer'), level: $('#level-value'), xp: $('#xp-fill'), xpText: $('#xp-text'), dash: $('#dash-chip'), combo: $('#combo-chip'), comboValue: $('#combo-value'), boss: $('#boss-hud'), bossFill: $('#boss-fill'), bossName: $('#boss-name') };
  const SAVE_KEY = 'one-room-100-monsters-v1';
  const defaults = { bestScore: 0, bestTime: 0, sound: true, volume: .55, shake: true, numbers: true, reduced: false };
  function readSave() { try { return { ...defaults, ...JSON.parse(localStorage.getItem(SAVE_KEY) || '{}') }; } catch { return { ...defaults }; } }
  let save = readSave();
  function persist() { try { localStorage.setItem(SAVE_KEY, JSON.stringify(save)); } catch { /* Private browsing can disable storage. */ } }

  const state = { screen: 'title', runId: 0, time: 0, wave: 1, waveTime: 0, spawnClock: 0, kills: 0, score: 0, level: 1, xp: 0, xpNext: 8, combo: 0, comboTimer: 0, runTime: 0, totalSpawned: 0, event100: false, eventSlow: 0, shake: 0, toastUntil: 0, enemies: [], bullets: [], hostile: [], orbs: [], particles: [], numbers: [], pickups: [], upgrades: [], boss: null, keys: new Set(), pointer: { x: W / 2, y: H / 2, down: false }, last: 0, waveBreak: 0 };
  const player = { x: W / 2, y: H / 2, vx: 0, vy: 0, r: 12, speed: 205, hp: 100, maxHp: 100, armor: 0, damage: 18, rate: .32, shot: 0, projectileSpeed: 500, multishot: 1, pierce: 0, crit: .06, pickup: 74, regen: 0, dashCd: 0, dashMax: 2.1, dashTime: 0, invuln: 0, aim: 0, healOnKill: 0 };
  const types = {
    basic: { name: 'Drifter', r: 11, hp: 28, speed: 61, dmg: 10, color: '#e9685a', xp: 1, score: 80 },
    fast: { name: 'Skitter', r: 8, hp: 17, speed: 111, dmg: 8, color: '#f1b55c', xp: 1, score: 110 },
    tank: { name: 'Brute', r: 18, hp: 128, speed: 36, dmg: 19, color: '#aa6a8f', xp: 3, score: 230 },
    ranged: { name: 'Spitter', r: 12, hp: 40, speed: 45, dmg: 8, color: '#74bd9a', xp: 2, score: 160 },
    splitter: { name: 'Nestling', r: 14, hp: 51, speed: 57, dmg: 11, color: '#9b83dc', xp: 2, score: 180 },
    mini: { name: 'The Warden', r: 29, hp: 980, speed: 40, dmg: 24, color: '#f3555d', xp: 12, score: 2200 }
  };
  const upgrades = [
    ['hot-lead','HOT LEAD','+22% weapon damage','⚒',()=>player.damage*=1.22], ['quick-hands','QUICK HANDS','+18% fire rate','»',()=>player.rate*=.84], ['extra-round','EXTRA ROUND','Fire one more shot','✣',()=>player.multishot=Math.min(5,player.multishot+1)],
    ['long-barrel','LONG BARREL','+25% projectile speed','➤',()=>player.projectileSpeed*=1.25], ['deep-mag','DEEP MAG','Bullets pierce +1 enemy','↠',()=>player.pierce++], ['steady-aim','STEADY AIM','+8% critical chance','⌖',()=>player.crit=Math.min(.5,player.crit+.08)],
    ['field-dressing','FIELD DRESSING','Restore 30 health now','✚',()=>player.hp=Math.min(player.maxHp,player.hp+30)], ['reinforced','REINFORCED','+25 max health and heal','⬡',()=>{player.maxHp+=25;player.hp=Math.min(player.maxHp,player.hp+25)}], ['light-feet','LIGHT FEET','+12% movement speed','⌁',()=>player.speed*=1.12],
    ['phase-drive','PHASE DRIVE','Dash recharges 25% faster','ϟ',()=>player.dashMax*=.75], ['magnet-core','MAGNET CORE','+45 pickup radius','◉',()=>player.pickup+=45], ['kinetic','KINETIC IMPACT','+20% damage and knockback','✦',()=>{player.damage*=1.2;player.knockback=(player.knockback||0)+75}],
    ['scavenger','SCAVENGER','+35% experience gained','◇',()=>player.xpMult=(player.xpMult||1)*1.35], ['second-wind','SECOND WIND','Regenerate 1 health / sec','♡',()=>player.regen+=1], ['executioner','EXECUTIONER','+35% damage to elites','†',()=>player.bossDamage=(player.bossDamage||1)*1.35],
    ['vampire','VAMPIRIC','Kills restore 1 health','♥',()=>player.healOnKill++], ['lucky-break','LUCKY BREAK','+5% critical chance','✧',()=>player.crit=Math.min(.55,player.crit+.05)], ['wide-shot','WIDE SHOT','+18% projectile size','●',()=>player.bulletSize=(player.bulletSize||4)*1.18]
  ].map(([id,name,desc,icon,apply])=>({id,name,desc,icon,apply}));

  let audio = null;
  function beep(freq=300, duration=.06, type='square', volume=.05) {
    if (!save.sound || save.volume <= 0) return;
    try { audio ||= new (window.AudioContext || window.webkitAudioContext)(); if (audio.state === 'suspended') audio.resume(); const o=audio.createOscillator(),g=audio.createGain(); o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(45,freq*.55),audio.currentTime+duration);g.gain.setValueAtTime(volume*save.volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration); } catch { /* Audio is an enhancement, not a requirement. */ }
  }
  function soundButton() { $('#sound-toggle').classList.toggle('muted', !save.sound); $('#sound-toggle').style.color = save.sound ? '' : '#ff684c'; }
  function setToggle(id,key) { const el=$(id); el.setAttribute('aria-pressed',String(!!save[key])); el.onclick=()=>{save[key]=!save[key];el.setAttribute('aria-pressed',String(save[key]));persist()}; }
  function showPanel(id) { for (const el of document.querySelectorAll('.overlay .panel')) el.hidden = el.id !== id; ui.overlay.hidden = false; }
  function showToast(text,duration=1700) { ui.toast.textContent=text;ui.toast.hidden=false;state.toastUntil=performance.now()+duration; }
  function fmt(n) { return Math.floor(n).toString().padStart(6,'0'); }
  function fmtTime(t) { const s=Math.floor(t);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`; }
  function updateTitleStats() { $('#best-title').textContent=fmt(save.bestScore);$('#best-foot').textContent=fmtTime(save.bestTime); }
  function resize() { const rect=canvas.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0); }
  window.addEventListener('resize',resize);resize();
  function startRun() {
    Object.assign(player,{x:W/2,y:H/2,vx:0,vy:0,speed:205,hp:100,maxHp:100,armor:0,damage:18,rate:.32,shot:0,projectileSpeed:500,multishot:1,pierce:0,crit:.06,pickup:74,regen:0,dashCd:0,dashMax:2.1,dashTime:0,invuln:0,aim:0,healOnKill:0,knockback:0,xpMult:1,bossDamage:1,bulletSize:4});
    Object.assign(state,{screen:'playing',runId:state.runId+1,time:0,wave:1,waveTime:0,spawnClock:1.25,kills:0,score:0,level:1,xp:0,xpNext:8,combo:0,comboTimer:0,runTime:0,totalSpawned:0,event100:false,eventSlow:0,shake:0,enemies:[],bullets:[],hostile:[],orbs:[],particles:[],numbers:[],pickups:[],upgrades:[],boss:null,waveBreak:0});
    ui.overlay.hidden=true;ui.hud.hidden=false;ui.pause.hidden=false;updateHud();beep(440,.14,'triangle',.07);state.last=performance.now();
  }
  function setScreen(screen,panel) { state.screen=screen;if(panel){showPanel(panel);ui.hud.hidden=true;ui.pause.hidden=true}else{ui.overlay.hidden=true;ui.hud.hidden=false;ui.pause.hidden=false} }
  function pause() { if(state.screen==='playing'){setScreen('paused','pause-panel');}else if(state.screen==='paused'){state.screen='playing';ui.overlay.hidden=true;ui.hud.hidden=false;ui.pause.hidden=false;state.last=performance.now()} }
  function restartToMenu(){state.screen='title';ui.hud.hidden=true;ui.pause.hidden=true;showPanel('title-panel');updateTitleStats()}
  function endRun() {
    state.screen='gameover';ui.boss.hidden=true;ui.hud.hidden=true;ui.pause.hidden=true;
    const record=state.score>save.bestScore;save.bestScore=Math.max(save.bestScore,state.score);save.bestTime=Math.max(save.bestTime,state.runTime);persist();updateTitleStats();
    $('#final-score').textContent=fmt(state.score);$('#final-time').textContent=fmtTime(state.runTime);$('#final-kills').textContent=state.kills;$('#final-wave').textContent=`${String(state.wave).padStart(2,'0')} / ${String(state.level).padStart(2,'0')}`;$('#record-note').hidden=!record;
    $('#run-verdict').textContent=state.kills>=100?'The room remembers your name.':'You made them work for it.';showPanel('gameover-panel');beep(115,.45,'sawtooth',.1);
  }
  function spawn(typeKey, x, y, child=false) {
    const t=types[typeKey],edge=Math.floor(Math.random()*4);if(x==null){if(edge===0){x=WALL+8;y=50+Math.random()*(H-100)}else if(edge===1){x=W-WALL-8;y=50+Math.random()*(H-100)}else if(edge===2){x=60+Math.random()*(W-120);y=WALL+8}else{x=60+Math.random()*(W-120);y=H-WALL-8}}
    const dist=Math.hypot(x-player.x,y-player.y);if(!child&&dist<125){x=x< W/2?W-WALL-18:WALL+18;y=Math.max(WALL+18,Math.min(H-WALL-18,y+(y<H/2?90:-90)))}
    const scale=1+Math.max(0,state.runTime-35)*.004+(state.wave-1)*.08;
    const e={type:typeKey,x,y,vx:0,vy:0,r:t.r,hp:t.hp*scale,maxHp:t.hp*scale,speed:t.speed*(1+Math.max(0,state.runTime-90)*.00075),dmg:t.dmg*(1+(state.wave-1)*.06),color:t.color,xp:t.xp,score:t.score,hit:0,attack:Math.random()*1.5,phase:Math.random()*6.28,child,knock:0};state.enemies.push(e);state.totalSpawned++;if(typeKey==='mini'){state.boss=e;ui.boss.hidden=false;ui.bossName.textContent='THE WARDEN';ui.bossFill.style.width='100%';showToast('WARDEN INBOUND',2300);beep(90,.45,'sawtooth',.1)}return e;
  }
  function chooseEnemy(){const t=state.runTime;if(state.wave%5===0&&state.waveTime<1.3&&state.waveBreak===0&&!state.boss){return 'mini'}const r=Math.random();if(t<20)return 'basic';if(t<50)return r<.72?'basic':'fast';if(t<90)return r<.45?'basic':r<.68?'fast':r<.84?'tank':'splitter';return r<.25?'basic':r<.45?'fast':r<.65?'tank':r<.82?'ranged':'splitter'}
  function particle(x,y,color,count=5,speed=110){if(save.reduced)count=Math.ceil(count*.38);for(let i=0;i<count&&state.particles.length<850;i++){const a=Math.random()*Math.PI*2,s=speed*(.3+Math.random()*.9);state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.22+Math.random()*.38,max:.6,size:1+Math.random()*2.7,color})}}
  function damageNumber(x,y,value,crit=false){if(save.numbers)state.numbers.push({x,y,value:Math.round(value),life:.7,crit})}
  function fire(){if(state.screen!=='playing'||state.waveBreak>0||player.shot>0)return;player.shot=player.rate;const count=player.multishot,spread=.105;for(let i=0;i<count;i++){const offset=(i-(count-1)/2)*spread,a=player.aim+offset,crit=Math.random()<player.crit;state.bullets.push({x:player.x+Math.cos(a)*15,y:player.y+Math.sin(a)*15,vx:Math.cos(a)*player.projectileSpeed,vy:Math.sin(a)*player.projectileSpeed,r:player.bulletSize||4,damage:player.damage*(crit?2:1),life:1.3,pierce:player.pierce,crit});}particle(player.x+Math.cos(player.aim)*15,player.y+Math.sin(player.aim)*15,'#e4f3bd',2,35);beep(440,.035,'square',.035)}
  function dash(){if(player.dashCd>0||state.screen!=='playing')return;let dx=(state.keys.has('d')||state.keys.has('ArrowRight')?1:0)-(state.keys.has('a')||state.keys.has('ArrowLeft')?1:0),dy=(state.keys.has('s')||state.keys.has('ArrowDown')?1:0)-(state.keys.has('w')||state.keys.has('ArrowUp')?1:0),len=Math.hypot(dx,dy);if(!len){dx=Math.cos(player.aim);dy=Math.sin(player.aim)}else{dx/=len;dy/=len}player.vx=dx*690;player.vy=dy*690;player.dashTime=.19;player.dashCd=player.dashMax;player.invuln=.27;beep(170,.13,'sawtooth',.07)}
  function damageEnemy(e,amount,crit=false){e.hp-=amount;e.hit=.09;damageNumber(e.x,e.y-e.r,amount,crit);particle(e.x,e.y,crit?'#fff0a0':e.color,crit?7:3,crit?145:85);if(player.knockback)e.knock=player.knockback;if(e.hp<=0)killEnemy(e)}
  function killEnemy(e){if(!e||e.dead)return;e.dead=true;state.kills++;state.combo++;state.comboTimer=2.1;state.score+=Math.floor(e.score*(1+Math.min(2,state.combo/10)));if(player.healOnKill)player.hp=Math.min(player.maxHp,player.hp+player.healOnKill);particle(e.x,e.y,e.color,e.type==='mini'?32:10,e.type==='mini'?220:130);state.orbs.push({x:e.x,y:e.y,r:e.type==='mini'?6:4,xp:e.xp,life:22,phase:Math.random()*6});if(e.type==='splitter'&&!e.child){spawn('fast',e.x-9,e.y-5,true);spawn('fast',e.x+9,e.y+5,true)}if(e===state.boss){state.boss=null;ui.boss.hidden=true;state.score+=3000;state.waveBreak=3;showToast('WARDEN ELIMINATED',2100);state.pickups.push({x:e.x,y:e.y,type:'heal',life:14});beep(610,.32,'triangle',.11)}if(state.kills===100&&!state.event100){state.event100=true;state.eventSlow=1.4;state.score+=5000;player.hp=Math.min(player.maxHp,player.hp+35);showToast('100 MONSTERS!',2400);beep(800,.45,'triangle',.12);const runId=state.runId;setTimeout(()=>{if(state.runId===runId&&state.screen==='playing'&&!state.boss){spawn('mini');state.wave=Math.max(state.wave,5);updateHud()}},1450)}if(Math.random()<.035&&e.type!=='mini')state.pickups.push({x:e.x,y:e.y,type:Math.random()<.55?'heal':'burst',life:12})}
  function levelUp(){state.level++;state.upgrades=[];const choices=[...upgrades].sort(()=>Math.random()-.5).slice(0,3);state.upgrades=choices;setScreen('upgrade','upgrade-panel');const host=$('#upgrade-cards');host.innerHTML='';choices.forEach((u,i)=>{const b=document.createElement('button');b.className='upgrade-card';b.innerHTML=`<div class="rarity">FIELD MOD // ${['COMMON','RARE','ELITE'][Math.floor(Math.random()*3)]}</div><span class="upgrade-icon">${u.icon}</span><h3>${u.name}</h3><p>${u.desc}</p><span class="key-hint">[ ${i+1} ]</span>`;b.onclick=()=>chooseUpgrade(i);host.appendChild(b)});beep(690,.2,'triangle',.08)}
  function chooseUpgrade(i){const u=state.upgrades[i];if(!u)return;u.apply();state.xp-=state.xpNext;state.xpNext=Math.floor(8+state.level*3.2+Math.pow(state.level,1.32)*1.5);state.screen='playing';ui.overlay.hidden=true;ui.hud.hidden=false;ui.pause.hidden=false;showToast(u.name+' ACQUIRED',1200);updateHud();state.last=performance.now()}
  function collectXp(amount){state.xp+=amount*(player.xpMult||1);beep(760+Math.random()*120,.045,'sine',.025);while(state.xp>=state.xpNext&&state.screen==='playing'){levelUp();break}}
  function updateHud(){ui.health.style.width=`${100*player.hp/player.maxHp}%`;ui.healthText.textContent=`${Math.ceil(player.hp)} / ${player.maxHp}`;ui.wave.textContent=String(state.wave).padStart(2,'0');ui.score.textContent=fmt(state.score);ui.kills.textContent=`${state.kills} KILLS`;ui.timer.textContent=fmtTime(state.runTime);ui.level.textContent=String(state.level).padStart(2,'0');ui.xp.style.width=`${100*state.xp/state.xpNext}%`;ui.xpText.textContent=`${Math.floor(state.xp)} / ${state.xpNext}`;ui.dash.innerHTML=player.dashCd<=0?'SPACE <b>DASH READY</b>':`SPACE <b>${player.dashCd.toFixed(1)}s</b>`;ui.combo.hidden=state.combo<5;ui.comboValue.textContent=`×${(1+Math.min(2,Math.floor(state.combo/5)*.5)).toFixed(1)}`;if(state.boss){ui.boss.hidden=false;ui.bossFill.style.width=`${Math.max(0,100*state.boss.hp/state.boss.maxHp)}%`}}

  function update(dt){state.time+=dt;if(state.screen!=='playing')return;const worldDt=state.eventSlow>0?dt*.24:dt;state.eventSlow=Math.max(0,state.eventSlow-dt);state.runTime+=dt;state.waveTime+=dt;if(state.waveBreak>0){state.waveBreak-=dt;if(state.waveBreak<=0){state.wave++;state.waveTime=0;showToast(`WAVE ${String(state.wave).padStart(2,'0')}`,1400)}}
    if(state.comboTimer>0){state.comboTimer-=dt;if(state.comboTimer<=0)state.combo=0}if(player.regen)player.hp=Math.min(player.maxHp,player.hp+player.regen*dt);player.shot-=dt;player.dashCd=Math.max(0,player.dashCd-dt);player.invuln=Math.max(0,player.invuln-dt);player.dashTime=Math.max(0,player.dashTime-dt);
    let dx=(state.keys.has('d')||state.keys.has('ArrowRight')?1:0)-(state.keys.has('a')||state.keys.has('ArrowLeft')?1:0),dy=(state.keys.has('s')||state.keys.has('ArrowDown')?1:0)-(state.keys.has('w')||state.keys.has('ArrowUp')?1:0),len=Math.hypot(dx,dy);if(len){dx/=len;dy/=len}const accel=player.dashTime>0?0:Math.min(1,dt*12);player.vx+=(dx*player.speed-player.vx)*accel;player.vy+=(dy*player.speed-player.vy)*accel;if(!len&&player.dashTime<=0){player.vx*=Math.max(0,1-dt*8);player.vy*=Math.max(0,1-dt*8)}player.x=Math.max(WALL+player.r,Math.min(W-WALL-player.r,player.x+player.vx*dt));player.y=Math.max(WALL+player.r,Math.min(H-WALL-player.r,player.y+player.vy*dt));player.aim=Math.atan2(state.pointer.y-player.y,state.pointer.x-player.x);if(state.pointer.down)fire();
    if(state.waveBreak<=0&&!state.boss){state.spawnClock-=dt;if(state.spawnClock<=0){const cap=Math.min(115,10+Math.floor(state.runTime/3.4));if(state.enemies.length<cap)spawn(chooseEnemy());state.spawnClock=Math.max(.24,1.12-state.runTime*.0035)*(.72+Math.random()*.55)}}
    for(const e of state.enemies){if(e.dead)continue;e.hit=Math.max(0,e.hit-dt);e.phase+=dt*2;const vx=player.x-e.x,vy=player.y-e.y,d=Math.hypot(vx,vy)||1;let moveX=0,moveY=0;if(e.type==='ranged'){if(d>225){moveX=vx/d;moveY=vy/d}else if(d<155){moveX=-vx/d;moveY=-vy/d}e.attack-=dt;if(e.attack<=0&&d<390){const a=Math.atan2(vy,vx);state.hostile.push({x:e.x,y:e.y,vx:Math.cos(a)*190,vy:Math.sin(a)*190,r:5,life:3,dmg:e.dmg,color:e.color});e.attack=1.8+Math.random()*.6;particle(e.x,e.y,e.color,3,50)}}else{moveX=vx/d;moveY=vy/d}
      let sx=0,sy=0;for(const other of state.enemies){if(other===e||other.dead)continue;const ax=e.x-other.x,ay=e.y-other.y,q=ax*ax+ay*ay;if(q>0&&q<(e.r+other.r+8)**2){const f=1/Math.sqrt(q);sx+=ax*f;sy+=ay*f}}const sl=Math.hypot(sx,sy)||1;let speed=e.speed*(e.type==='mini'?1+Math.sin(e.phase)*.14:1);e.vx=moveX*speed+(sx/sl)*Math.min(34,Math.hypot(sx,sy)*9)+(e.knock?Math.cos(e.phase)*e.knock:0);e.vy=moveY*speed+(sy/sl)*Math.min(34,Math.hypot(sx,sy)*9)+(e.knock?Math.sin(e.phase)*e.knock:0);e.knock=Math.max(0,e.knock-dt*130);e.x=Math.max(WALL+e.r,Math.min(W-WALL-e.r,e.x+e.vx*worldDt));e.y=Math.max(WALL+e.r,Math.min(H-WALL-e.r,e.y+e.vy*worldDt));if(d<e.r+player.r+3&&player.invuln<=0){const hit=Math.max(1,e.dmg-player.armor);player.hp-=hit;player.invuln=.58;player.vx+=(player.x-e.x)/d*170;player.vy+=(player.y-e.y)/d*170;state.shake=save.shake?7:0;particle(player.x,player.y,'#ff725e',9,130);beep(125,.13,'sawtooth',.08);if(player.hp<=0){endRun();return}}}
    const nearby=state.enemies.filter(e=>!e.dead);for(const b of state.bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;for(const e of nearby){if(e.dead)continue;const rr=e.r+b.r,ax=b.x-e.x,ay=b.y-e.y;if(ax*ax+ay*ay<rr*rr){const mult=e.type==='mini'?(player.bossDamage||1):1;damageEnemy(e,b.damage*mult,b.crit);if(b.pierce>0)b.pierce--;else{b.life=-1;break}}}}state.bullets=state.bullets.filter(b=>b.life>0&&b.x>WALL&&b.x<W-WALL&&b.y>WALL&&b.y<H-WALL);
    for(const b of state.hostile){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;const q=(b.x-player.x)**2+(b.y-player.y)**2;if(q<(b.r+player.r)**2&&player.invuln<=0){player.hp-=Math.max(1,b.dmg-player.armor);player.invuln=.62;b.life=-1;state.shake=save.shake?5:0;particle(player.x,player.y,'#ff725e',7,95);beep(130,.11,'sawtooth',.08);if(player.hp<=0){endRun();return}}}state.hostile=state.hostile.filter(b=>b.life>0);
    for(const o of state.orbs){o.life-=dt;const ox=player.x-o.x,oy=player.y-o.y,d=Math.hypot(ox,oy)||1;if(d<player.pickup||d<26){const sp=d<26?300:330*(1-d/player.pickup);o.x+=ox/d*sp*dt;o.y+=oy/d*sp*dt}if(d<player.r+o.r+4){o.life=0;collectXp(o.xp)}}state.orbs=state.orbs.filter(o=>o.life>0);
    for(const p of state.pickups){p.life-=dt;const d=Math.hypot(player.x-p.x,player.y-p.y);if(d<player.r+13){if(p.type==='heal'){player.hp=Math.min(player.maxHp,player.hp+25);showToast('PATCHED UP +25',1000)}else{player.damage*=1.4;setTimeout(()=>{if(state.screen==='playing')player.damage/=1.4},9000);showToast('OVERDRIVE // 9 SEC',1000)}p.life=0;beep(590,.14,'triangle',.08)}}state.pickups=state.pickups.filter(p=>p.life>0);
    for(const p of state.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.max(0,1-dt*2.5);p.vy*=Math.max(0,1-dt*2.5);p.life-=dt}state.particles=state.particles.filter(p=>p.life>0);for(const n of state.numbers){n.y-=26*dt;n.life-=dt}state.numbers=state.numbers.filter(n=>n.life>0);
    if(state.runTime>=state.wave*42&&state.waveBreak<=0&&!state.boss){state.waveBreak=2.4;showToast(`WAVE ${String(state.wave+1).padStart(2,'0')} INCOMING`,1300)}updateHud();
  }

  function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
  function render(){ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0);ctx.clearRect(0,0,W,H);const shake=state.screen==='playing'&&save.shake?state.shake:0;if(shake)state.shake=Math.max(0,state.shake-.35);ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawRoom();for(const o of state.orbs)drawOrb(o);for(const p of state.pickups)drawPickup(p);for(const b of state.bullets)drawBullet(b,false);for(const b of state.hostile)drawBullet(b,true);for(const e of state.enemies)if(!e.dead)drawEnemy(e);drawPlayer();for(const p of state.particles)drawParticle(p);for(const n of state.numbers)drawNumber(n);ctx.restore();if(state.screen==='title'||state.screen==='paused'||state.screen==='upgrade'||state.screen==='gameover')drawVignette();if(state.toast&&!ui.toast.hidden&&performance.now()>state.toastUntil)ui.toast.hidden=true;if(state.screen==='playing'&&state.waveBreak>0)drawWaveBreak();requestAnimationFrame(render)}
  function drawRoom(){ctx.fillStyle='#111821';ctx.fillRect(0,0,W,H);ctx.fillStyle='#151d26';ctx.fillRect(WALL,H*0+WALL,W-2*WALL,H-2*WALL);ctx.save();ctx.beginPath();ctx.rect(WALL,WALL,W-2*WALL,H-2*WALL);ctx.clip();for(let y=WALL;y<H-WALL;y+=34){for(let x=WALL;x<W-WALL;x+=34){const alt=((x-WALL)/34+(y-WALL)/34)%2;ctx.fillStyle=alt?'#171f29':'#19222c';ctx.fillRect(x,y,34,34);ctx.strokeStyle='#202a35';ctx.lineWidth=1;ctx.strokeRect(x+.5,y+.5,33,33)}}ctx.strokeStyle='#343e49';ctx.lineWidth=2;ctx.setLineDash([7,8]);ctx.strokeRect(78,78,W-156,H-156);ctx.setLineDash([]);ctx.restore();ctx.fillStyle='#252e38';ctx.fillRect(0,0,W,WALL);ctx.fillRect(0,H-WALL,W,WALL);ctx.fillRect(0,WALL,WALL,H-2*WALL);ctx.fillRect(W-WALL,WALL,WALL,H-2*WALL);ctx.strokeStyle='#59636f';ctx.lineWidth=1;ctx.strokeRect(WALL+.5,WALL+.5,W-2*WALL-1,H-2*WALL-1);
    for(const [x,y] of [[68,68],[W-68,68],[68,H-68],[W-68,H-68]]){ctx.fillStyle='#38434e';ctx.fillRect(x-14,y-14,28,28);ctx.fillStyle='#1a222b';ctx.fillRect(x-10,y-10,20,20);ctx.fillStyle='#59646f';ctx.fillRect(x-7,y-7,14,3);ctx.fillRect(x-7,y+4,14,3);ctx.fillStyle='#c8f169';ctx.globalAlpha=.45;ctx.fillRect(x-2,y-2,4,4);ctx.globalAlpha=1}ctx.strokeStyle='#2e3945';ctx.lineWidth=3;ctx.beginPath();ctx.arc(W/2,H/2,34,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(W/2,H/2,28,0,Math.PI*2);ctx.strokeStyle='#222c37';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle='#333d49';ctx.font='9px DM Mono';ctx.textAlign='center';ctx.fillText('SECTOR 01 // CONTAINMENT',W/2,H-13);
    if(state.runTime>45&&Math.floor(state.time*2)%2===0){ctx.fillStyle='#ff3c3c';ctx.globalAlpha=.16;ctx.fillRect(WALL,WALL,W-2*WALL,4);ctx.fillRect(WALL,H-WALL-4,W-2*WALL,4);ctx.globalAlpha=1}}
  function drawEnemy(e){const r=e.r,pulse=1+Math.sin(e.phase*2)*.035;ctx.save();ctx.translate(e.x,e.y);ctx.scale(pulse,pulse);ctx.shadowColor=e.color;ctx.shadowBlur=e.type==='mini'?19:9;ctx.fillStyle=e.hit>0?'#fff2dc':e.color;ctx.beginPath();if(e.type==='fast'){ctx.moveTo(-r,-r*.65);ctx.lineTo(r,0);ctx.lineTo(-r,r*.65)}else if(e.type==='tank'||e.type==='mini'){const n=e.type==='mini'?8:6;for(let i=0;i<n;i++){let a=Math.PI*2*i/n-Math.PI/2,x=Math.cos(a)*r,y=Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath()}else if(e.type==='splitter'){ctx.moveTo(0,-r);ctx.lineTo(r,r*.5);ctx.lineTo(0,r);ctx.lineTo(-r,r*.5);ctx.closePath()}else ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#171820';ctx.beginPath();ctx.arc(-r*.3,-r*.12,Math.max(1.5,r*.12),0,Math.PI*2);ctx.arc(r*.3,-r*.12,Math.max(1.5,r*.12),0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff8';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-r*.25,r*.3);ctx.lineTo(r*.25,r*.3);ctx.stroke();if(e.hp<e.maxHp||e.type==='mini'){ctx.fillStyle='#10151c';ctx.fillRect(-r, -r-7,r*2,3);ctx.fillStyle=e.type==='mini'?'#ff6964':'#f0bd75';ctx.fillRect(-r,-r-7,r*2*Math.max(0,e.hp/e.maxHp),3)}ctx.restore()}
  function drawPlayer(){const flash=player.invuln>0&&Math.floor(state.time*20)%2===0;ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.aim);if(player.dashTime>0){ctx.globalAlpha=.26;ctx.fillStyle='#c8f169';ctx.beginPath();ctx.ellipse(-14,0,21,10,0,0,Math.PI*2);ctx.fill()}ctx.shadowColor='#c8f169';ctx.shadowBlur=18;ctx.fillStyle=flash?'#fff':(state.screen==='playing'&&state.time%1<.06&&player.invuln>0?'#fff':'#c8f169');ctx.beginPath();ctx.arc(0,0,player.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#232c24';ctx.beginPath();ctx.arc(0,0,player.r*.56,0,Math.PI*2);ctx.fill();ctx.fillStyle='#dbe6be';ctx.fillRect(3,-3,16,6);ctx.fillStyle='#f8f9e9';ctx.fillRect(13,-2,7,4);ctx.restore();if(player.hp<player.maxHp){ctx.fillStyle='#1a2028';ctx.fillRect(player.x-15,player.y-23,30,3);ctx.fillStyle=player.hp/player.maxHp<.3?'#ff5c55':'#c8f169';ctx.fillRect(player.x-15,player.y-23,30*Math.max(0,player.hp/player.maxHp),3)}}
  function drawBullet(b,hostile){ctx.fillStyle=hostile?'#f38572':'#efffc8';ctx.shadowColor=hostile?'#ff674f':'#d7ff8c';ctx.shadowBlur=hostile?11:8;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}
  function drawOrb(o){const pulse=1+Math.sin(state.time*5+o.phase)*.19;ctx.save();ctx.translate(o.x,o.y);ctx.rotate(Math.PI/4);ctx.fillStyle='#b8a9ff';ctx.shadowColor='#9b80ff';ctx.shadowBlur=12;ctx.fillRect(-o.r*pulse,-o.r*pulse,o.r*2*pulse,o.r*2*pulse);ctx.restore();ctx.shadowBlur=0}
  function drawPickup(p){const c=p.type==='heal'?'#c8f169':'#ffbd65';ctx.save();ctx.translate(p.x,p.y);ctx.rotate(Math.PI/4);ctx.fillStyle=c;ctx.shadowColor=c;ctx.shadowBlur=15;ctx.fillRect(-8,-8,16,16);ctx.restore();ctx.shadowBlur=0;ctx.fillStyle='#141820';ctx.font='bold 12px sans-serif';ctx.textAlign='center';ctx.fillText(p.type==='heal'?'+':'ϟ',p.x,p.y+4)}
  function drawParticle(p){ctx.globalAlpha=Math.min(1,p.life/.2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size);ctx.globalAlpha=1}
  function drawNumber(n){ctx.globalAlpha=Math.min(1,n.life*2);ctx.fillStyle=n.crit?'#fff0a0':'#f4d4bf';ctx.font=`${n.crit?'bold ':''}${n.crit?12:10}px DM Mono`;ctx.textAlign='center';ctx.fillText(n.value,n.x,n.y);ctx.globalAlpha=1}
  function drawVignette(){const g=ctx.createRadialGradient(W/2,H/2,100,W/2,H/2,590);g.addColorStop(0,'transparent');g.addColorStop(1,'#05070bb5');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
  function drawWaveBreak(){ctx.fillStyle='#c8f169';ctx.globalAlpha=.06;ctx.fillRect(WALL,WALL,W-2*WALL,H-2*WALL);ctx.globalAlpha=1}

  function pointerPos(e){const r=canvas.getBoundingClientRect();state.pointer.x=(e.clientX-r.left)/r.width*W;state.pointer.y=(e.clientY-r.top)/r.height*H}
  canvas.addEventListener('pointermove',pointerPos);canvas.addEventListener('pointerdown',e=>{if(e.button===0){state.pointer.down=true;pointerPos(e);if(state.screen==='playing')fire()}});window.addEventListener('pointerup',e=>{if(e.button===0)state.pointer.down=false});canvas.addEventListener('contextmenu',e=>e.preventDefault());
  window.addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(k))e.preventDefault();state.keys.add(k);if(k==='Escape'){if(state.screen==='playing'||state.screen==='paused')pause();else if(state.screen==='how'||state.screen==='settings')showPanel('title-panel')}if(k===' '&&state.screen==='playing')dash();if(state.screen==='upgrade'&&['1','2','3'].includes(k))chooseUpgrade(Number(k)-1)});window.addEventListener('keyup',e=>state.keys.delete(e.key.length===1?e.key.toLowerCase():e.key));window.addEventListener('blur',()=>{state.pointer.down=false;state.keys.clear();if(state.screen==='playing')pause()});

  $('#play-button').onclick=startRun;$('#how-button').onclick=()=>{state.screen='how';showPanel('how-panel')};$('#how-back').onclick=()=>{state.screen='title';showPanel('title-panel')};$('#settings-button').onclick=()=>{state.screen='settings';showPanel('settings-panel')};$('#settings-back').onclick=()=>{state.screen='title';showPanel('title-panel')};$('#resume-button').onclick=pause;$('#pause-button').onclick=pause;$('#pause-restart').onclick=startRun;$('#pause-menu').onclick=restartToMenu;$('#retry-button').onclick=startRun;$('#gameover-menu').onclick=restartToMenu;$('#sound-toggle').onclick=()=>{save.sound=!save.sound;soundButton();persist();if(save.sound)beep(500,.08,'triangle')};$('#fullscreen').onclick=()=>{if(!document.fullscreenElement)document.querySelector('.game-frame').requestFullscreen?.();else document.exitFullscreen?.()};$('#volume-slider').value=String(Math.round(save.volume*100));$('#volume-slider').oninput=e=>{save.volume=Number(e.target.value)/100;persist()};setToggle('#shake-toggle','shake');setToggle('#numbers-toggle','numbers');setToggle('#effects-toggle','reduced');soundButton();updateTitleStats();

  function frame(now){const dt=Math.min(.05,Math.max(0,(now-state.last)/1000));state.last=now;update(dt);requestAnimationFrame(frame)}state.last=performance.now();requestAnimationFrame(frame);requestAnimationFrame(render);
})();
